[book]
authors = ["Gregory Wainer"]
language = "en"
multilingual = false
src = "src"
title = "Rocketry at Virginia Tech"
description = "This is the knowledge base for the Rocketry at Virginia Tech design team."
