[book]
authors = ["Gregory Wainer"]
language = "en"
multilingual = false
src = "src"
title = "Rocketry at Virginia Tech"
description = "This is the knowledge base for the Rocketry at Virginia Tech design team."

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
smart-punctuation = true
mathjax-support = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]

git-repository-url = "https://github.com/RocketryVT/knowledge-base"
git-repository-icon = "fa-github"

[output.html.print]
enable = true
page-break = true

