site_name: Rocketry at Virginia Tech Knowledge Base
site_url: https://rocketryatvirginiatech.org/knowledge-base/
repo_url: https://github.com/RocketryVT/knowledge-base
edit_uri: edit/main/docs/
theme:
  name: material
  logo: assets/favicon.ico
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    # - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
  palette:
    # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
nav:
  - Home: README.md
  - Contributing: contributing.md
  - Summary: SUMMARY.md
  - 2024-2025: 
      - 2024-2025/README.md
      - Design: 2024-2025/Design/README.md
      - Hardware: 2024-2025/Hardware/README.md
      - Software: 2024-2025/Software/README.md
  - Ansys:
      - Ansys/README.md
      - Cloud Compute: Ansys/cloud-compute.md
  - Hardware:
      - Hardware/README.md
      - Active Drag System: Hardware/ActiveDragSystem/ads.md
      - Batteris: Hardware/Batteries/README.md
  - Software:
      - Software/README.md
      - Filters: Software/Filters/README.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - abbr
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  